### ISSUE TITLE
Resolve NYC update and __coverage__ plugin

### ISSUE THREAD

**Issue by localnerve** [localnerve/react-pwa-reference#119]
As of NYC 7.0.0, babel-plugin-__coverage__ has either been absorbed or otherwise is no longer compatible. Resolve this package divergence.

Work was done on https://github.com/dtinth/babel-plugin-__coverage__/issues/42

Update NYC and update/replace babel-plugin-__coverage__ as appropriate.

Ref: https://github.com/istanbuljs/nyc/commit/1ca42dcf600e7012fbb26bffe56ee7681620b98b
Ref: https://github.com/localnerve/element-size-reporter/commit/1511d35535accc2fdc34d9a1e379cb16ed5af149

**Comment by localnerve** [comment]
The main thing holding this up is there appears to be no way to get it to cover local node_modules.

**Comment by bcoe** [comment]
Likewise, mind giving this a shot?

`npm cache clear; npm i nyc@next`, with configuration that looks something like this:

```json
{
  "nyc": {
     "exclude": []
   }
}
```

**Comment by localnerve** [comment]
I'm looking forward to doing this tonight! Thanks for the heads up.

**Comment by localnerve** [comment]
@bcoe Here's the report: 
> Did **NOT** get local node_modules. **Did** get coverage of all other directories.

I double checked that nyc 8.0.0-candidate was indeed installed.
Babel-plugin-istanbul 1.0.3 installed.

Here is output/configs:

### Install
```shell
$ npm cache clear; npm i nyc@next
- lodash.keys@4.0.7 node_modules/nyc/node_modules/lodash.keys
- lodash.rest@4.0.3 node_modules/nyc/node_modules/lodash.rest
react-pwa-reference@0.1.0 /Users/agrant/projects/react-pwa-reference
├── lodash@4.14.2
└── nyc@8.0.0-candidate  extraneous
```

### .babelrc
```javascript
{
  "plugins": [
    "lodash"
  ],
  "presets": [
    "es2015",
    "react"
  ],
  "ignore": [
    "react-pwa-boilerplate/node_modules/**",
    "reports/*",
    "dist/*"
  ],
  "env": {
    "cover": {
      "plugins": [
        [
          "istanbul", {
            "exclude": [
            ]
          }
        ]
      ]
    }
  }
}
```

### package.json snippet
```javascript
  "nyc": {
    "sourceMap": false,
    "instrument": false,
    "exclude": [],
    "report-dir": "reports/coverage"
  },
```

### Full command
Note usage of NYC_CWD
```javacript
"test:cover": "rimraf .nyc_output/ && cross-env BABEL_ENV=cover npm run build:output && cross-env NYC_CWD=output nyc --reporter=lcov npm run _test",
```

### output directory
```shell
agrant at Alexs-MacBook-Pro in ~/projects/react-pwa-reference/output on master [!]
$ ll
total 0
drwxr-xr-x  8 agrant  staff  272 Aug 12 19:08 application/
drwxr-xr-x  5 agrant  staff  170 Aug 12 19:08 node_modules/
drwxr-xr-x  7 agrant  staff  238 Aug 12 19:08 tests/
``

Got coverage for application and tests, not node_modules.
