### ISSUE TITLE
documentation unclear

### ISSUE THREAD

**Issue by shreycp** [localnerve/react-pwa-reference#541]
Can you please write a better documentation, so that I may know what is being served by the server at first when the url is hit, and thereafter the flow of the code.

Thanks

**Comment by localnerve** [comment]
Thanks for the tip on what you would find useful.

Until documentation is produced, to illuminate what is being served by the server, here's a brief trace of how something is rendered. Please let me know if this is helpful to you.

1. [npm start](https://github.com/localnerve/react-pwa-reference/blob/961bd01d1ec2341d252f65e52103554df03567c6/package.json#L45) sets up an express middleware stack to serve the api and resources, initializes the data layer, and starts listening on a port.
    * The source for the file given to Node in the `npm start` command is [this source file](https://github.com/localnerve/react-pwa-reference/blob/master/src/application/server/index.js)
2. [In server/index.js](https://github.com/localnerve/react-pwa-reference/blob/961bd01d1ec2341d252f65e52103554df03567c6/src/application/server/index.js#L77), the middleware that renders the application is [`main`](https://github.com/localnerve/react-pwa-reference/blob/master/src/application/server/main.js). This renders all application routes.

To render an application route it:  

A. Populates the Application Data Stores
    * [Get all app routes from the data service](https://github.com/localnerve/react-pwa-reference/blob/961bd01d1ec2341d252f65e52103554df03567c6/src/application/server/main.js#L102)
    * [Populates one-time initialization data](https://github.com/localnerve/react-pwa-reference/blob/961bd01d1ec2341d252f65e52103554df03567c6/src/application/server/main.js#L108)
    * [Get content for special, high-priority routes that don't rely on network](https://github.com/localnerve/react-pwa-reference/blob/961bd01d1ec2341d252f65e52103554df03567c6/src/application/server/main.js#L131)
    * [Execute the navigation for the requested route, populate results of that action](https://github.com/localnerve/react-pwa-reference/blob/961bd01d1ec2341d252f65e52103554df03567c6/src/application/server/main.js#L141)

B. Gathers Props to render the HTML
    * [Get inline styles](https://github.com/localnerve/react-pwa-reference/blob/961bd01d1ec2341d252f65e52103554df03567c6/src/application/server/main.js#L155)
    * [Get inline scripts](https://github.com/localnerve/react-pwa-reference/blob/961bd01d1ec2341d252f65e52103554df03567c6/src/application/server/main.js#L162)
    * [Get the rest of the props and render the HTML](https://github.com/localnerve/react-pwa-reference/blob/961bd01d1ec2341d252f65e52103554df03567c6/src/application/server/main.js#L169) [`in this function`](https://github.com/localnerve/react-pwa-reference/blob/961bd01d1ec2341d252f65e52103554df03567c6/src/application/server/main.js#L35)

C. [Renders the HTML](https://github.com/localnerve/react-pwa-reference/blob/961bd01d1ec2341d252f65e52103554df03567c6/src/application/server/main.js#L65)

If you found that useful, please let me know so I can get an idea of what documentation is useful.

**Comment by localnerve** [comment]
Hi there, I'm going to close after 18 days of no correspondence. If you're interested in supplying more specific information about what documentation would useful, please email me. Thanks again for your information.
